### ISSUE TITLE
Create Dashboard

### ISSUE THREAD

**Issue by CrispyBacon1999** [Hemlock5712/2024-Robot#11]
## Task Description

**Brief description:**
Drivers need to have a dashboard that has essential data on it when they're on the field. This would include things like autonomous pickers. Talk to drivers to find what information is actually helpful to them.

## Task Details

**To-Do:**
- [ ] Determine what info is helpful to drive team
  - [ ] Driver
  - [ ] Operator
  - [ ] Coach
- [ ] Implement this into networktables
- [ ] Create the dashboard
