### ISSUE TITLE
Limelight game piece tracking

### ISSUE THREAD

**Issue by CrispyBacon1999** [Hemlock5712/2024-Robot#19]
## Task Description

**Brief description:**
Limelight provides the ability to do color tracking. We could use this to track game pieces to automatically move to a position to grab them.

To do this, we need to configure the limelight to do color detection and return the position to the robot. It might be worth getting a white light that shines on the ground to reduce shadows as much as possible as well.

## Task Details

**To-Do:**
- [ ] Setup limelight
  - [ ] Determine contours
  - [ ] Return contours to robot
- [ ] Simulation with photonvision?
  - [ ] Setup sim IO implementation

**Additional Information:**
https://docs.limelightvision.io/docs/docs-limelight/pipeline-retro/color-filtering
https://docs.photonvision.org/en/latest/docs/simulation/simulation.html#simulation-support-in-photonlib
