### ISSUE TITLE
Center to game piece

### ISSUE THREAD

**Issue by CrispyBacon1999** [Hemlock5712/2024-Robot#20]
## Task Description

**Brief description:**
With working object detection, we can have the robot automatically align itself to game pieces.

**Related feature/issue:**
[Link to the main feature/issue that this task is associated with, if applicable.]

## Task Details

**To-Do:**
- [ ] Create command
  - [ ] Read values from limelight
  - [ ] Adjust robot position to a straight line in the direction of the game piece
- [ ] Map to button

**Comment by JosephTLockwood** [comment]
Duplicate of #19
