### ISSUE TITLE
Get Full SIM Running

### ISSUE THREAD

**Issue by JosephTLockwood** [Hemlock5712/2024-Robot#33]
## Task Description

Import CAD of our robot and code logic

## Task Details

**To-Do:**
- [ ] Import CAD into AdvantageScope
  - [ ] Get CAD from Chris
  - [ ] Subtask B
- [ ] Program AdvantageKit Logic
