### ISSUE TITLE
[Subsystem]: Intake

### ISSUE THREAD

**Issue by CrispyBacon1999** [Hemlock5712/2024-Robot#4]
## Task Description

**Brief description:**
Create the subsystem for the intake. This should handle the actual logic for each state the intake can be in.

**Related feature/issue:**
#1: IO Layer

## Task Details

**To-Do:**
- [ ] Basic subsystem setup
  - [ ] Intake in/out
  - [ ] Run/reverse wheels
